import json
import pathlib
import struct
from collections import Counter
import heapq

class HuffmanNode:
    def __init__(self, char, freq):
        self.char = char
        self.freq = freq
        self.left = None
        self.right = None

    def __lt__(self, other):
        return self.freq < other.freq

def build_huffman_tree(phoneme_strings):
    # Count frequencies of all characters
    freqs = Counter()
    for p in phoneme_strings:
        freqs.update(p)
    
    # Priority queue
    heap = [HuffmanNode(ch, f) for ch, f in freqs.items()]
    heapq.heapify(heap)
    
    if len(heap) == 0:
        return None, {}
    if len(heap) == 1:
        node = heap[0]
        return node, {node.char: '0'}
        
    while len(heap) > 1:
        left = heapq.heappop(heap)
        right = heapq.heappop(heap)
        merged = HuffmanNode(None, left.freq + right.freq)
        merged.left = left
        merged.right = right
        heapq.heappush(heap, merged)
        
    root = heap[0]
    
    codes = {}
    def build_codes(node, current_code):
        if node.char is not None:
            codes[node.char] = current_code
        else:
            build_codes(node.left, current_code + '0')
            build_codes(node.right, current_code + '1')
            
    build_codes(root, '')
    return root, codes

def get_shared_prefix_len(s1, s2):
    m = min(len(s1), len(s2))
    for i in range(m):
        if s1[i] != s2[i]:
            return i
    return m

def build_compressed_dictionary():
    in_path = pathlib.Path(__file__).parent.parent / "data" / "dictsource" / "de_DE_espeak_exceptions.json"
    exceptions = json.loads(in_path.read_text('utf-8'))
    
    words = sorted(exceptions.keys())
    
    # 1. Build Huffman tree for phonemes
    root, huff_codes = build_huffman_tree(exceptions.values())
    
    # 2. Serialize Huffman Tree for C
    c_huff_nodes = []
    def serialize_huffman(node):
        if node.char is not None:
            # Leaf node: right child is char, left is 0xFFFF (marked as leaf)
            c_huff_nodes.append(f"    {{0xFFFF, {ord(node.char)}}} /* LEAF: '{node.char}' */")
            return len(c_huff_nodes) - 1
        else:
            # Internal node
            idx = len(c_huff_nodes)
            c_huff_nodes.append("    {0, 0} /* INTERNAL (placeholder) */")
            left_idx = serialize_huffman(node.left)
            right_idx = serialize_huffman(node.right)
            c_huff_nodes[idx] = f"    {{{left_idx}, {right_idx}}} /* INTERNAL */"
            return idx
            
    serialize_huffman(root)
    
    # 3. Block compression (Front coding + Huffman)
    BLOCK_SIZE = 128
    blocks = []
    current_block_data = bytearray()
    block_index = [] # (first_word, byte_offset)
    
    for i, w in enumerate(words):
        if i % BLOCK_SIZE == 0:
            block_index.append((w, len(current_block_data)))
            prev_word = ""
        
        # Front coding
        shared = get_shared_prefix_len(w, prev_word)
        suffix = w[shared:].encode('utf-8')
        
        # Huffman encode phonemes
        phonemes = exceptions[w]
        bit_string = ''.join(huff_codes[ch] for ch in phonemes)
        # Pad with 1s to byte boundary
        padding = (8 - (len(bit_string) % 8)) % 8
        bit_string += '1' * padding
        
        huff_bytes = bytearray()
        for b in range(0, len(bit_string), 8):
            byte_val = int(bit_string[b:b+8], 2)
            huff_bytes.append(byte_val)
            
        # Write entry
        # Format: [shared_len (1 byte)] [suffix_len (1 byte)] [suffix_bytes] [huff_bits_len (2 bytes, LE)] [huff_bytes]
        current_block_data.append(shared)
        current_block_data.append(len(suffix))
        current_block_data.extend(suffix)
        
        huff_bits_len = len(''.join(huff_codes[ch] for ch in phonemes))
        if huff_bits_len > 65535:
            huff_bits_len = 65535
            
        current_block_data.append(huff_bits_len & 0xFF)
        current_block_data.append((huff_bits_len >> 8) & 0xFF)
        current_block_data.extend(huff_bytes)
        
        prev_word = w

    # 4. Generate C file
    c_code = """/**
 * @file espure_dict_compressed.c
 * @brief Compressed Dictionary (Front-Coded + Huffman)
 * Auto-generated by build_compressed_dict.py
 */

#include "espure_internal.h"
#include <stdint.h>
#include <stddef.h>

#ifdef CONFIG_ESPURE_DICT_HUFFMAN_TRIE

"""
    
    # Huffman Tree
    c_code += "typedef struct { uint16_t left; uint16_t right; } huff_node_t;\n\n"
    c_code += "static const huff_node_t DICT_HUFFMAN_TREE[] = {\n"
    c_code += ",\n".join(c_huff_nodes)
    c_code += "\n};\n\n"
    
    # Block Index
    c_code += "typedef struct { const char* first_word; uint32_t offset; } block_index_t;\n\n"
    c_code += f"static const block_index_t DICT_BLOCK_INDEX[{len(block_index)}] = {{\n"
    for w, off in block_index:
        w_esc = w.replace('"', '\\"')
        c_code += f'    {{"{w_esc}", {off}}},\n'
    c_code += "};\n\n"
    
    # Blob Data
    c_code += f"static const uint8_t DICT_BLOB_DATA[{len(current_block_data)}] = {{\n    "
    for i, b in enumerate(current_block_data):
        c_code += f"0x{b:02X}, "
        if (i + 1) % 16 == 0:
            c_code += "\n    "
    c_code += "\n};\n\n"
    
    c_code += """
// Search function to find a word in the compressed blob
espure_err_t espure_dict_compressed_lookup(const char* word, char* out_phonemes, size_t out_size) {
    size_t num_blocks = sizeof(DICT_BLOCK_INDEX) / sizeof(DICT_BLOCK_INDEX[0]);
    if (num_blocks == 0) return ESPURE_ERR_NOT_FOUND;
    
    // Binary search for the block
    int left = 0;
    int right = num_blocks - 1;
    int block_idx = 0;
    
    while (left <= right) {
        int mid = left + (right - left) / 2;
        int cmp = strcmp(word, DICT_BLOCK_INDEX[mid].first_word);
        
        if (cmp == 0) {
            block_idx = mid;
            break;
        } else if (cmp < 0) {
            right = mid - 1;
        } else {
            block_idx = mid;
            left = mid + 1;
        }
    }
    
    // Sequential scan within the block
    uint32_t offset = DICT_BLOCK_INDEX[block_idx].offset;
    uint32_t end_offset = (block_idx + 1 < num_blocks) ? DICT_BLOCK_INDEX[block_idx + 1].offset : sizeof(DICT_BLOB_DATA);
    
    char current_word[128] = {0};
    
    while (offset < end_offset) {
        uint8_t shared = DICT_BLOB_DATA[offset++];
        uint8_t suffix_len = DICT_BLOB_DATA[offset++];
        
        for (int i = 0; i < suffix_len; i++) {
            current_word[shared + i] = DICT_BLOB_DATA[offset++];
        }
        current_word[shared + suffix_len] = '\\0';
        
        uint16_t huff_bits_len = DICT_BLOB_DATA[offset++];
        huff_bits_len |= (uint16_t)DICT_BLOB_DATA[offset++] << 8;
        uint32_t huff_bytes_len = (huff_bits_len + 7) / 8;
        
        if (strcmp(word, current_word) == 0) {
            // Found! Decode Huffman
            size_t out_pos = 0;
            uint16_t node = 0; // root is always 0
            
            for (int bit = 0; bit < huff_bits_len; bit++) {
                uint8_t byte_val = DICT_BLOB_DATA[offset + (bit / 8)];
                int bit_val = (byte_val >> (7 - (bit % 8))) & 1;
                
                if (bit_val == 0) {
                    node = DICT_HUFFMAN_TREE[node].left;
                } else {
                    node = DICT_HUFFMAN_TREE[node].right;
                }
                
                if (DICT_HUFFMAN_TREE[node].left == 0xFFFF) { // Leaf
                    if (out_pos < out_size - 1) {
                        out_phonemes[out_pos++] = (char)DICT_HUFFMAN_TREE[node].right;
                    }
                    node = 0; // reset to root
                }
            }
            out_phonemes[out_pos] = '\\0';
            return ESPURE_OK;
        }
        
        // Skip huffman bytes and continue
        offset += huff_bytes_len;
    }
    
    return ESPURE_ERR_NOT_FOUND;
}
#endif // CONFIG_ESPURE_DICT_HUFFMAN_TRIE
"""

    out_path = pathlib.Path(__file__).parent.parent / "lang" / "de_DE" / "de_DE_dict_compressed.c"
    out_path.write_text(c_code, 'utf-8')
    print(f"Generated {out_path.name}: Blob size is {len(current_block_data)} bytes.")

if __name__ == "__main__":
    build_compressed_dictionary()
