/**
 * @file espure_phoneme.c
 * @brief Phoneme table management
 * 
 * Implements phoneme table loading from phsource/phonemes format.
 * Maps 1:1 to espeak-ng's phoneme.h / synthdata.c
 * 
 * Reference: .reference_codes/espure/espure/phoneme_tab.py
 * Agent Insight: Store phoneme data in PSRAM (94% confidence)
 */

#include "espure_internal.h"
#include <string.h>
#include <esp_log.h>

static const char* TAG = "espure_phoneme";

// Phoneme types (from phoneme.h)

/**
 * Phoneme table structure
 */
struct espure_phoneme_table_s {
    char lang[8];
    size_t num_phonemes;
    espure_phoneme_t* phonemes;  // Array in PSRAM
    size_t heap_used;
    const espure_config_t* config;
};

// Embedded phsource data (generated by embed_phsource.py)
extern const char espure_phsource_phonemes_test[];
extern const size_t espure_phsource_phonemes_test_size;

// Reserved phonemes (codes 1-33) - same in every language
static const struct {
    const char* mnemonic;
    uint8_t code;
} RESERVED_PHONEMES[] = {
    {"\x01", 1}, {"%", 2}, {"%%", 3}, {",", 4}, {",,", 5},
    {"'", 6}, {"''", 7}, {"=", 8}, {"_:", 9}, {"_", 10},
    {"_!", 11}, {":", 12}, {"@", 13}, {"@-", 14}, {"||", 15},
    {"*", 16}, {"1", 17}, {"#X1", 18}, {"?", 19}, {"-", 20},
    {"_^_", 21}, {"_X1", 22}, {"_|", 23}, {"_::", 24}, {"t#", 25},
    {"'!", 26}, {"_;_", 27}, {"#@", 28}, {"#a", 29}, {"#e", 30},
    {"#i", 31}, {"#o", 32}, {"#u", 33}
};

#define NUM_RESERVED_PHONEMES (sizeof(RESERVED_PHONEMES) / sizeof(RESERVED_PHONEMES[0]))

/**
 * Parse phoneme type from keyword
 */
/**
 * Initialize phoneme table with reserved phonemes
 */
static espure_err_t init_reserved_phonemes(espure_phoneme_table_t* table) {
    table->num_phonemes = NUM_RESERVED_PHONEMES;
    
    // Allocate phoneme array in PSRAM (Agent: 94% confidence)
    size_t alloc_size = NUM_RESERVED_PHONEMES * sizeof(espure_phoneme_t);
    table->phonemes = espure_calloc(NUM_RESERVED_PHONEMES, 
                                     sizeof(espure_phoneme_t),
                                     table->config);
    if (!table->phonemes) {
        ESP_LOGE(TAG, "Failed to allocate phoneme array (%zu bytes)", alloc_size);
        return ESPURE_ERR_NO_MEM;
    }
    
    ESP_LOGI(TAG, "Allocated phoneme array: %zu bytes in %s", 
             alloc_size, table->config->use_psram ? "PSRAM" : "DRAM");
    
    // Initialize reserved phonemes
    for (size_t i = 0; i < NUM_RESERVED_PHONEMES; i++) {
        espure_phoneme_t* ph = &table->phonemes[i];
        
        // Copy mnemonic (max 7 chars + null terminator)
        strlcpy(ph->mnemonic, RESERVED_PHONEMES[i].mnemonic, 7);
        ph->mnemonic[7] = '\0';
        
        ph->code = RESERVED_PHONEMES[i].code;
        ph->type = ESPURE_PHONEME_INVALID;  // Will be set when parsing phsource
        ph->ipa = NULL;
        ph->stress_type = 0;
        ph->flags = 0;
    }
    
    table->heap_used += alloc_size;
    
    ESP_LOGI(TAG, "Initialized %d reserved phonemes", NUM_RESERVED_PHONEMES);
    return ESPURE_OK;
}

espure_err_t espure_phoneme_table_init(const char* lang,
                                       const espure_config_t* config,
                                       espure_phoneme_table_t** out) {
    if (!lang || !config || !out) {
        return ESPURE_ERR_INVALID_ARG;
    }
    
    ESP_LOGI(TAG, "Initializing phoneme table for '%s'", lang);
    
    // Allocate table structure in DRAM (small, accessed frequently)
    espure_phoneme_table_t* table = espure_calloc(1, 
        sizeof(espure_phoneme_table_t), config);
    if (!table) {
        ESP_LOGE(TAG, "Failed to allocate phoneme table structure");
        return ESPURE_ERR_NO_MEM;
    }
    
    strlcpy(table->lang, lang, sizeof(table->lang));
    table->config = config;
    table->heap_used = sizeof(espure_phoneme_table_t);
    
    // Initialize reserved phonemes
    espure_err_t err = init_reserved_phonemes(table);
    if (err != ESPURE_OK) {
        espure_free(table);
        return err;
    }
    
    // Parse phsource data and merge with reserved phonemes
    ESP_LOGI(TAG, "Parsing phsource/phonemes data...");
    
    // Use static buffer for parsed phonemes (avoid stack overflow)
    static espure_phoneme_t temp_phonemes[128];
    memset(temp_phonemes, 0, sizeof(temp_phonemes));
    
    size_t num_parsed = 0;
    err = espure_parse_phsource(espure_phsource_phonemes_test,
                                 temp_phonemes,
                                 128,
                                 &num_parsed);
    
    if (err != ESPURE_OK) {
        ESP_LOGW(TAG, "Failed to parse phsource data: %d", err);
        // Continue with only reserved phonemes
    } else {
        ESP_LOGI(TAG, "Parsed %zu phonemes from phsource", num_parsed);
        
        // Merge parsed phonemes with reserved phonemes
        if (num_parsed > 0) {
            size_t total_phonemes = table->num_phonemes + num_parsed;
            
            // Reallocate phoneme array
            espure_phoneme_t* new_phonemes = espure_realloc(
                table->phonemes,
                total_phonemes * sizeof(espure_phoneme_t),
                config
            );
            
            if (new_phonemes) {
                table->phonemes = new_phonemes;
                
                // Copy parsed phonemes after reserved ones
                memcpy(&table->phonemes[table->num_phonemes],
                       temp_phonemes,
                       num_parsed * sizeof(espure_phoneme_t));
                
                table->num_phonemes = total_phonemes;
                table->heap_used += num_parsed * sizeof(espure_phoneme_t);
                
                ESP_LOGI(TAG, "Merged phonemes: %zu total (%d reserved + %zu parsed)",
                         total_phonemes, NUM_RESERVED_PHONEMES, num_parsed);
            } else {
                ESP_LOGW(TAG, "Failed to allocate memory for merged phonemes");
            }
        }
    }
    
    ESP_LOGI(TAG, "Phoneme table initialized: %zu phonemes, %zu bytes", 
             table->num_phonemes, table->heap_used);
    
    *out = table;
    return ESPURE_OK;
}

void espure_phoneme_table_deinit(espure_phoneme_table_t* table) {
    if (!table) {
        return;
    }
    
    ESP_LOGI(TAG, "Deinitializing phoneme table");
    
    // Free phoneme array (in PSRAM)
    if (table->phonemes) {
        // Free IPA strings
        for (size_t i = 0; i < table->num_phonemes; i++) {
            if (table->phonemes[i].ipa) {
                espure_free(table->phonemes[i].ipa);
            }
        }
        espure_free(table->phonemes);
    }
    
    // Free table structure
    espure_free(table);
}

size_t espure_phoneme_table_size(const espure_phoneme_table_t* table) {
    return table ? table->heap_used : 0;
}

/**
 * @brief Look up phoneme by mnemonic
 * 
 * Linear search through phoneme table (~60 phonemes, fast enough).
 * 
 * @param table Phoneme table
 * @param mnemonic Phoneme mnemonic (e.g. "r", "r/", "@")
 * @return Phoneme pointer or NULL if not found
 */
const espure_phoneme_t* espure_phoneme_lookup(
    const espure_phoneme_table_t* table,
    const char* mnemonic
) {
    if (!table || !mnemonic) {
        return NULL;
    }
    
    // Linear search (table is small, ~60 phonemes)
    for (size_t i = 0; i < table->num_phonemes; i++) {
        if (strcmp(table->phonemes[i].mnemonic, mnemonic) == 0) {
            return &table->phonemes[i];
        }
    }
    
    ESP_LOGD(TAG, "Phoneme not found: '%s'", mnemonic);
    return NULL;
}
